app:
  version: 0.0.1

spring:
  application:
    name: g33-hateoas
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db_test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger